// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uzser.CoreServices.Data;

#nullable disable

namespace Uzser.CoreServices.Migrations.ErpDb
{
    [DbContext(typeof(ErpDbContext))]
    [Migration("20250703145123_UpdateCountryColumnToInt")]
    partial class UpdateCountryColumnToInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Uzser.CoreServices.Models.DTO.Cities", b =>
                {
                    b.Property<string>("CODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("COUNTRY")
                        .HasColumnType("int");

                    b.Property<int>("LOGICALREF")
                        .HasColumnType("int");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("UZS_VW_CITIES", (string)null);
                });

            modelBuilder.Entity("Uzser.CoreServices.Models.Entities.Customer", b =>
                {
                    b.Property<string>("ADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CREATEDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATEUSER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUSTOMERCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUSTOMERNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FLOWID")
                        .HasColumnType("int");

                    b.Property<int?>("PAYMENTTYPE")
                        .HasColumnType("int");

                    b.Property<int?>("STATUS")
                        .HasColumnType("int");

                    b.Property<string>("TAXOFFICE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TELEPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPDATEDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATEUSER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VKNTC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WFSTATE")
                        .HasColumnType("int");

                    b.ToTable("UZS_VW_CUSTOMER");

                    b.ToView("UZS_VW_CUSTOMER", (string)null);
                });

            modelBuilder.Entity("Uzser.CoreServices.Models.Entities.Departments", b =>
                {
                    b.Property<short>("DEPARTMENT_CODE")
                        .HasColumnType("smallint");

                    b.Property<string>("DEPARTMENT_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("UZS_VW_DEPARTMENTS");

                    b.ToView("UZS_VW_DEPARTMENTS", (string)null);
                });

            modelBuilder.Entity("Uzser.CoreServices.Models.Entities.Stock", b =>
                {
                    b.Property<string>("STOCK_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STOCK_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("UZS_VW_STOCK");

                    b.ToView("UZS_VW_STOCK", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
