  
CREATE VIEW UZS_VW_CUSTOMER AS      
SELECT       
    CAPIBLOCK_CREADEDDATE AS CREATEDATE,      
    CAST(CAPIBLOCK_CREATEDBY AS nvarchar(MAX)) AS CREATEUSER,      
    CAPIBLOCK_MODIFIEDDATE AS UPDATEDATE,      
    CAST(CAPIBLOCK_MODIFIEDBY AS nvarchar(MAX)) AS UPDATEUSER,      
    0 AS WFSTATE,      
    CODE COLLATE SQL_Latin1_General_CP1_CI_AS AS CUSTOMERCODE,      
    DEFINITION_ COLLATE SQL_Latin1_General_CP1_CI_AS AS CUSTOMERNAME,      
    TAXNR COLLATE SQL_Latin1_General_CP1_CI_AS AS VKNTC,      
    TAXOFFICE COLLATE SQL_Latin1_General_CP1_CI_AS AS TAXOFFICE,      
    ADDR1 COLLATE SQL_Latin1_General_CP1_CI_AS AS ADDRESS,      
    TELNRS1 COLLATE SQL_Latin1_General_CP1_CI_AS AS TELEPHONE,      
    PAYMENTREF AS PAYMENTTYPE,      
    EMAILADDR COLLATE SQL_Latin1_General_CP1_CI_AS AS EMAIL,      
    0 AS FLOWID,  
 NULL as STATUS  
FROM TIGER3ENT..LG_001_CLCARD      
WHERE CODE IS NOT NULL      
      
UNION ALL      
      
SELECT       
    CREATEDATE,      
    CREATEUSER,      
    UPDATEDATE,      
    UPDATEUSER,      
    WFSTATE,      
    CUSTOMERCODE COLLATE SQL_Latin1_General_CP1_CI_AS,      
    CUSTOMERNAME COLLATE SQL_Latin1_General_CP1_CI_AS,      
    VKNTC COLLATE SQL_Latin1_General_CP1_CI_AS,      
    TaxOffice COLLATE SQL_Latin1_General_CP1_CI_AS,      
    Address COLLATE SQL_Latin1_General_CP1_CI_AS,      
    Telephone COLLATE SQL_Latin1_General_CP1_CI_AS,      
    PaymentType,      
    Email COLLATE SQL_Latin1_General_CP1_CI_AS AS EMAIL,      
    FLOWID,  
 STATUS  
FROM FURKANTEST..UZS_TBL_CUSTOMER ;